"""user: hashed_password -> password

Revision ID: 1ff2bf4a01d9
Revises: 490784c3a8d7
Create Date: 2025-10-09 17:40:14.068009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ff2bf4a01d9'
down_revision: Union[str, Sequence[str], None] = '490784c3a8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
